# весь код

## Скачиваем файлы с Яндекс Диска

Строго запускайте **ЯЧЕЙКИ ПО ПОРЯДКУ**

In [1]:
!pip install requests

Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (2.32.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests) (3.4.5)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests) (2026.2.25)

### Кабардинский текст

In [2]:
import requests

public_key = "https://disk.360.yandex.ru/d/zLqgEBtsQuUacA"

url = "https://cloud-api.yandex.net/v1/disk/public/resources/download"

r = requests.get(url, params={"public_key": public_key})

download_url = r.json()["href"]

print(download_url)

https://downloader.disk.yandex.ru/disk/d7311f7397187eb63ab723fa6b6aeb5fd1f6d94b2de13b8e733a33eae6836301/69b9c968/fKqInKw3d7bLFOeFnMGnhDIdN8aRRICXNU5VpCQ3WrrT4yXk2HHkS3MMWbQJ4_2D65q-6hWI3uLoNBsDcBizhHSL4GkRlCSEFDUavI647TOr8npumZHI4midPdWhecNq?uid=0&filename=Kabard_NoOCR_balanced_sampled_generated_gt.zip&disposition=attachment&hash=X0sNPvl8F5WPFJcKSLO4Xwwt8VkEHQSo3ZrcFz5PYNJd35gsLljx8/qW3FxpKuc6EkI0e0it/P53JjBKdrjFug%3D%3D%3A&limit=0&content_type=application%2Fzip&owner_uid=1130000061394466&fsize=352393834&hid=8589d05794364fb121b8769ce3442365&media_type=compressed&tknv=v3

In [3]:
!wget "$download_url" -O Kabard_NoOCR_balanced_sampled_generated_gt.zip

--2026-03-17 17:36:40--  https://downloader.disk.yandex.ru/disk/d7311f7397187eb63ab723fa6b6aeb5fd1f6d94b2de13b8e733a33eae6836301/69b9c968/fKqInKw3d7bLFOeFnMGnhDIdN8aRRICXNU5VpCQ3WrrT4yXk2HHkS3MMWbQJ4_2D65q-6hWI3uLoNBsDcBizhHSL4GkRlCSEFDUavI647TOr8npumZHI4midPdWhecNq?uid=0&filename=Kabard_NoOCR_balanced_sampled_generated_gt.zip&disposition=attachment&hash=X0sNPvl8F5WPFJcKSLO4Xwwt8VkEHQSo3ZrcFz5PYNJd35gsLljx8/qW3FxpKuc6EkI0e0it/P53JjBKdrjFug%3D%3D%3A&limit=0&content_type=application%2Fzip&owner_uid=1130000061394466&fsize=352393834&hid=8589d05794364fb121b8769ce3442365&media_type=compressed&tknv=v3
Resolving downloader.disk.yandex.ru (downloader.disk.yandex.ru)... 77.88.21.127, 2a02:6b8::2:127
Connecting to downloader.disk.yandex.ru (downloader.disk.yandex.ru)|77.88.21.127|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://s571sas.storage.yandex.net/rdisk/d7311f7397187eb63ab723fa6b6aeb5fd1f6d94b2de13b8e733a33eae6836301/69b9c968/fKqInKw3d7bLFOeFnMGnhDIdN8aRRICXNU5VpCQ3WrrT4yXk2HHkS3MMWbQJ4_2D65q-6hWI3uLoNBsDcBizhHSL4GkRlCSEFDUavI647TOr8npumZHI4midPdWhecNq?uid=0&filename=Kabard_NoOCR_balanced_sampled_generated_gt.zip&disposition=attachment&hash=X0sNPvl8F5WPFJcKSLO4Xwwt8VkEHQSo3ZrcFz5PYNJd35gsLljx8/qW3FxpKuc6EkI0e0it/P53JjBKdrjFug%3D%3D%3A&limit=0&content_type=application%2Fzip&owner_uid=1130000061394466&fsize=352393834&hid=8589d05794364fb121b8769ce3442365&media_type=compressed&tknv=v3&ts=64d3f21772a00&s=c3c066edae265aeed9110db3e0f970d9e0511d005126b772f3043a640db1ef2a&pb=U2FsdGVkX19qRC05KzVgccVGTn_ttHAsH1OylBgK8J6alDs6iONjkNp7W7rv6T6qZK2waIiP7WYTreKQAV-Nz_5Hg97x6bBENqPxuan49zYypOazLrGbAzkUqu-KtAkq [following]
--2026-03-17 17:36:41--  https://s571sas.storage.yandex.net/rdisk/d7311f7397187eb63ab723fa6b6aeb5fd1f6d94b2de13b8e733a33eae6836301/69b9c968/fKqInKw3d7bLFOeFnMGnhDIdN8aRRICXNU5VpCQ3WrrT4yXk2HHkS3MMWbQJ4_2D65q-6hWI3uLoNBsDcBizhHSL4GkRlCSEFDUavI647TOr8npumZHI4midPdWhecNq?uid=0&filename=Kabard_NoOCR_balanced_sampled_generated_gt.zip&disposition=attachment&hash=X0sNPvl8F5WPFJcKSLO4Xwwt8VkEHQSo3ZrcFz5PYNJd35gsLljx8/qW3FxpKuc6EkI0e0it/P53JjBKdrjFug%3D%3D%3A&limit=0&content_type=application%2Fzip&owner_uid=1130000061394466&fsize=352393834&hid=8589d05794364fb121b8769ce3442365&media_type=compressed&tknv=v3&ts=64d3f21772a00&s=c3c066edae265aeed9110db3e0f970d9e0511d005126b772f3043a640db1ef2a&pb=U2FsdGVkX19qRC05KzVgccVGTn_ttHAsH1OylBgK8J6alDs6iONjkNp7W7rv6T6qZK2waIiP7WYTreKQAV-Nz_5Hg97x6bBENqPxuan49zYypOazLrGbAzkUqu-KtAkq
Resolving s571sas.storage.yandex.net (s571sas.storage.yandex.net)... 37.9.68.32, 2a02:6b8:c02:e30:0:41af:6742:143a
Connecting to s571sas.storage.yandex.net (s571sas.storage.yandex.net)|37.9.68.32|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 352393834 (336M) [application/zip]
Saving to: ‘Kabard_NoOCR_balanced_sampled_generated_gt.zip’

Kabard_NoOCR_balanc 100%[===================>] 336.07M  21.6MB/s    in 18s

2026-03-17 17:37:00 (18.6 MB/s) - ‘Kabard_NoOCR_balanced_sampled_generated_gt.zip’ saved [352393834/352393834]

Кабардинский картинки

In [4]:
import requests

public_key = "https://disk.360.yandex.ru/d/BSdYV4wx_PDnqQ"

url = "https://cloud-api.yandex.net/v1/disk/public/resources/download"

r = requests.get(url, params={"public_key": public_key})

download_url = r.json()["href"]

print(download_url)

https://downloader.disk.yandex.ru/disk/4f3c14a8b8c33dbc43eeb4b500a270007eabd6aba149cd63c5f3c69280efa7c4/69b9c97d/fKqInKw3d7bLFOeFnMGnhGVWt_RVxY7KSMudEexmWAtBcMYYJjEO8ZVVAMdjrstKPWZBBdJu-4ad4DxflUOd1J9MNMSs4ZnxIk2lIhGYOv-r8npumZHI4midPdWhecNq?uid=0&filename=Kabard_NoOCR_balanced_sampled_generated_images.zip&disposition=attachment&hash=X0sNPvl8F5WPFJcKSLO4X6Y3s0%2BgKNzIqObjgtfRru4i%2BEaJJUP5z3l/XhNNe0B8EkI0e0it/P53JjBKdrjFug%3D%3D%3A&limit=0&content_type=application%2Fzip&owner_uid=1130000061394466&fsize=13494729818&hid=fb93073e2d9ce17220dff596f7982208&media_type=compressed&tknv=v3

In [5]:
!wget "$download_url" -O Kabard_NoOCR_balanced_sampled_generated_images.zip

--2026-03-17 17:37:01--  https://downloader.disk.yandex.ru/disk/4f3c14a8b8c33dbc43eeb4b500a270007eabd6aba149cd63c5f3c69280efa7c4/69b9c97d/fKqInKw3d7bLFOeFnMGnhGVWt_RVxY7KSMudEexmWAtBcMYYJjEO8ZVVAMdjrstKPWZBBdJu-4ad4DxflUOd1J9MNMSs4ZnxIk2lIhGYOv-r8npumZHI4midPdWhecNq?uid=0&filename=Kabard_NoOCR_balanced_sampled_generated_images.zip&disposition=attachment&hash=X0sNPvl8F5WPFJcKSLO4X6Y3s0%2BgKNzIqObjgtfRru4i%2BEaJJUP5z3l/XhNNe0B8EkI0e0it/P53JjBKdrjFug%3D%3D%3A&limit=0&content_type=application%2Fzip&owner_uid=1130000061394466&fsize=13494729818&hid=fb93073e2d9ce17220dff596f7982208&media_type=compressed&tknv=v3
Resolving downloader.disk.yandex.ru (downloader.disk.yandex.ru)... 77.88.21.127, 2a02:6b8::2:127
Connecting to downloader.disk.yandex.ru (downloader.disk.yandex.ru)|77.88.21.127|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://s85klg.storage.yandex.net/rdisk/4f3c14a8b8c33dbc43eeb4b500a270007eabd6aba149cd63c5f3c69280efa7c4/69b9c97d/fKqInKw3d7bLFOeFnMGnhGVWt_RVxY7KSMudEexmWAtBcMYYJjEO8ZVVAMdjrstKPWZBBdJu-4ad4DxflUOd1J9MNMSs4ZnxIk2lIhGYOv-r8npumZHI4midPdWhecNq?uid=0&filename=Kabard_NoOCR_balanced_sampled_generated_images.zip&disposition=attachment&hash=X0sNPvl8F5WPFJcKSLO4X6Y3s0%2BgKNzIqObjgtfRru4i%2BEaJJUP5z3l/XhNNe0B8EkI0e0it/P53JjBKdrjFug%3D%3D%3A&limit=0&content_type=application%2Fzip&owner_uid=1130000061394466&fsize=13494729818&hid=fb93073e2d9ce17220dff596f7982208&media_type=compressed&tknv=v3&ts=64d3f22b79940&s=7057340c20e70483b4b1d38db528407b8687b25395432a8e297140e78c2e998b&pb=U2FsdGVkX189C8cTogdBwZ7IrFaqfjQnKMGKSCHcxgrZbftYY9hzEipP3ujAc74TNEvgJ4KYw-YxbU1cA-Jih3KfudR9oUOiK7g91mneOWWIDpZIbwfiM_HFNFihzrWP [following]
--2026-03-17 17:37:02--  https://s85klg.storage.yandex.net/rdisk/4f3c14a8b8c33dbc43eeb4b500a270007eabd6aba149cd63c5f3c69280efa7c4/69b9c97d/fKqInKw3d7bLFOeFnMGnhGVWt_RVxY7KSMudEexmWAtBcMYYJjEO8ZVVAMdjrstKPWZBBdJu-4ad4DxflUOd1J9MNMSs4ZnxIk2lIhGYOv-r8npumZHI4midPdWhecNq?uid=0&filename=Kabard_NoOCR_balanced_sampled_generated_images.zip&disposition=attachment&hash=X0sNPvl8F5WPFJcKSLO4X6Y3s0%2BgKNzIqObjgtfRru4i%2BEaJJUP5z3l/XhNNe0B8EkI0e0it/P53JjBKdrjFug%3D%3D%3A&limit=0&content_type=application%2Fzip&owner_uid=1130000061394466&fsize=13494729818&hid=fb93073e2d9ce17220dff596f7982208&media_type=compressed&tknv=v3&ts=64d3f22b79940&s=7057340c20e70483b4b1d38db528407b8687b25395432a8e297140e78c2e998b&pb=U2FsdGVkX189C8cTogdBwZ7IrFaqfjQnKMGKSCHcxgrZbftYY9hzEipP3ujAc74TNEvgJ4KYw-YxbU1cA-Jih3KfudR9oUOiK7g91mneOWWIDpZIbwfiM_HFNFihzrWP
Resolving s85klg.storage.yandex.net (s85klg.storage.yandex.net)... 5.255.221.85, 2a02:6b8:c41:98:0:41af:b54c:5daf
Connecting to s85klg.storage.yandex.net (s85klg.storage.yandex.net)|5.255.221.85|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 13494729818 (13G) [application/zip]
Saving to: ‘Kabard_NoOCR_balanced_sampled_generated_images.zip’

Kabard_NoOCR_balanc 100%[===================>]  12.57G  21.9MB/s    in 10m 13s

2026-03-17 17:47:16 (21.0 MB/s) - ‘Kabard_NoOCR_balanced_sampled_generated_images.zip’ saved [13494729818/13494729818]

Разархивируем файлы по папкам

In [6]:
!unzip /content/Kabard_NoOCR_balanced_sampled_generated_gt.zip -d /content/kab_gt
!unzip /content/Kabard_NoOCR_balanced_sampled_generated_images.zip -d /content/kab_img

Выходные данные были обрезаны до нескольких последних строк (5000).
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_096500_Sans_0_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_097000_Mono_0_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_095041_Serif_0_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_097341_Sans_0_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_094608_Serif_0_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_099374_Mono_0_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_090444_Sans_1_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_094513_Mono_1_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_093003_Mono_0_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_094658_Serif_0_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_097741_Sans_0_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_091776_Mono_0_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_090779_Sans_0_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_091720_Sans_1_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_093274_Mono_1_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_094002_Mono_1_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_096729_Sans_1_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_092393_Sans_0_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_092409_Mono_0_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_094646_Sans_1_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_090061_Sans_1_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_091524_Serif_0_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_097892_Serif_0_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_099023_Mono_1_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_097548_Sans_1_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_099389_Sans_1_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_091709_Sans_0_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_099948_Sans_1_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_099663_Sans_0_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_091711_Serif_1_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_095078_Mono_1_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_092773_Mono_0_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_095470_Sans_0_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_098797_Serif_1_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_092224_Mono_1_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_092181_Sans_0_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_090877_Sans_0_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_092638_Serif_1_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_093960_Sans_1_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_092138_Serif_0_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_094759_Mono_1_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_093121_Serif_1_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_095898_Serif_0_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_098913_Serif_1_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_099434_Mono_1_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_097263_Serif_0_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_099673_Sans_1_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_098221_Serif_1_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_092162_Sans_0_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_095226_Mono_0_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_090132_Sans_0_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_094566_Sans_1_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_098949_Serif_0_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_094055_Sans_0_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_093459_Mono_1_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_097049_Serif_0_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_094993_Serif_0_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_096756_Sans_1_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_092969_Sans_1_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_096372_Serif_0_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_092952_Sans_0_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_096851_Serif_0_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_095233_Sans_0_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_092191_Mono_1_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_094796_Serif_0_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_090344_Mono_1_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_093614_Serif_0_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_096507_Sans_1_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_099610_Mono_0_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_095067_Sans_0_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_091987_Sans_0_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_092858_Serif_0_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_095348_Serif_1_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_096247_Mono_1_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_094753_Serif_1_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_090894_Sans_0_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_090326_Mono_1_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_099404_Serif_0_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_096463_Sans_0_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_097398_Serif_0_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_098464_Mono_1_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_095463_Sans_1_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_099847_Mono_0_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_093559_Sans_0_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_096820_Mono_0_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_098520_Mono_1_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_091732_Mono_1_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_097982_Mono_1_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_093672_Serif_1_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_094371_Serif_1_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_099837_Mono_1_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_091084_Mono_1_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_093300_Sans_1_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_095282_Serif_1_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_091717_Sans_0_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_094398_Serif_1_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_097898_Sans_0_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_097506_Sans_0_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_092989_Serif_0_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_094800_Mono_0_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_095564_Sans_0_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_092586_Sans_1_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_096022_Mono_0_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_092970_Serif_1_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_095158_Mono_1_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_095633_Serif_0_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_090864_Serif_0_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_097005_Mono_1_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_097061_Serif_1_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_092041_Mono_0_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_094799_Sans_0_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_098131_Serif_0_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_096030_Sans_0_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_097246_Serif_1_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_098315_Mono_1_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_096026_Mono_1_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_098924_Sans_1_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_095739_Serif_1_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_096308_Serif_1_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_097942_Serif_1_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_091073_Sans_1_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_092379_Mono_1_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_092326_Serif_1_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_091122_Mono_1_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_092326_Sans_1_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_098665_Mono_0_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_099792_Serif_1_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_095600_Mono_0_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_092427_Mono_0_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_096344_Serif_0_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_092728_Mono_0_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_096832_Sans_0_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_090515_Sans_0_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_093211_Serif_1_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_096860_Mono_1_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_092693_Serif_0_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_096938_Serif_1_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_091193_Mono_1_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_093128_Mono_1_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_094251_Mono_1_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_094626_Serif_0_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_098105_Sans_1_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_090562_Mono_0_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_094042_Serif_1_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_098398_Serif_0_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_094838_Mono_0_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_096184_Serif_1_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_092372_Mono_0_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_097300_Sans_0_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_097634_Sans_1_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_095500_Mono_1_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_095741_Serif_1_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_091227_Mono_0_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_096600_Mono_0_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_097047_Mono_1_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_093425_Mono_0_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_096928_Serif_1_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_095601_Serif_1_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_095034_Mono_1_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_096825_Sans_0_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_091845_Mono_1_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_095959_Serif_1_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_091962_Mono_0_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_094942_Serif_0_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_091395_Serif_1_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_093867_Sans_0_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_096337_Serif_1_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_092695_Mono_0_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_094988_Sans_1_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_092745_Serif_0_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_092632_Mono_0_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_093060_Serif_1_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_093244_Mono_1_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_096107_Serif_1_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_098295_Sans_0_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_092617_Serif_1_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_092380_Serif_0_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_097977_Serif_1_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_099672_Sans_0_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_099199_Serif_0_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_090516_Serif_0_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_090387_Serif_1_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_095302_Sans_1_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_090936_Sans_0_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_098684_Sans_0_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_093830_Serif_0_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_096586_Sans_0_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_091683_Serif_1_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_098545_Serif_1_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_097678_Serif_0_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_096328_Serif_0_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_091373_Sans_0_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_091974_Mono_0_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_095121_Sans_0_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_091600_Mono_1_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_095698_Sans_1_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_090218_Serif_1_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_093436_Serif_0_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_099478_Serif_0_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_098949_Sans_0_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_098747_Sans_1_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_097582_Serif_1_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_094083_Mono_0_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_097099_Serif_1_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_090610_Mono_0_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_099292_Serif_1_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_098393_Serif_0_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_090963_Sans_0_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_092415_Mono_1_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_096486_Sans_1_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_096677_Mono_1_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_090061_Mono_0_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_099885_Serif_0_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_098312_Sans_1_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_092523_Serif_0_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_095782_Sans_0_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_093167_Serif_1_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_097436_Mono_0_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_094628_Mono_1_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_093378_Serif_0_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_099694_Mono_1_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_098593_Sans_1_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_091342_Mono_0_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_097099_Sans_1_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_096721_Serif_1_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_097537_Sans_0_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_097125_Sans_1_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_094904_Mono_0_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_098832_Serif_0_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_096165_Mono_1_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_096660_Serif_1_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_091508_Serif_1_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_090540_Sans_0_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_095419_Serif_1_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_099662_Mono_0_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_094529_Mono_1_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_093300_Serif_0_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_092280_Serif_0_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_093762_Sans_1_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_098581_Mono_0_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_090186_Mono_0_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_095100_Mono_0_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_097553_Sans_0_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_097736_Sans_0_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_095452_Mono_0_1.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_090793_Mono_0_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_093669_Mono_0_0.jpg
  inflating: /content/kab_img/Kabard_NoOCR_balanced_sampled_094156_Serif_0_1.jpg

Теперь все делим 90/5/5

Сейчас делим кабардинский

In [7]:
import os

base = "/content/kab_dataset"

for split in ["train","valid","test"]:
    os.makedirs(f"{base}/{split}/images", exist_ok=True)
    os.makedirs(f"{base}/{split}/gt", exist_ok=True)

In [8]:
import os
import shutil
import re

img_dir = "/content/kab_img"
gt_dir = "/content/kab_gt"

pattern = re.compile(r"_(\d{6})_")

for img in os.listdir(img_dir):

    if not img.endswith(".jpg"):
        continue

    num = int(pattern.search(img).group(1))

    if num <= 90000:
        split = "train"
    elif num <= 95000:
        split = "valid"
    else:
        split = "test"

    img_src = os.path.join(img_dir, img)
    gt_src = os.path.join(gt_dir, img.replace(".jpg",".gt.txt"))

    img_dst = f"{base}/{split}/images/{img}"
    gt_dst = f"{base}/{split}/gt/{img.replace('.jpg','.gt.txt')}"

    shutil.move(img_src, img_dst)
    shutil.move(gt_src, gt_dst)

In [9]:
for split in ["train","valid","test"]:
    print(split)
    print("images:", len(os.listdir(f"{base}/{split}/images")))
    print("gt:", len(os.listdir(f"{base}/{split}/gt")))
    print()

train
images: 1080000
gt: 1080000

valid
images: 60000
gt: 60000

test
images: 60000
gt: 60000

In [10]:
import os
import re
import random

def reduce_renders_per_text(img_dir, gt_dir, keep=4):

    random.seed(42)

    pattern = re.compile(r"_(\d{6})_")
    groups = {}

    for img in sorted(os.listdir(img_dir)):

        if not img.endswith(".jpg"):
            continue

        m = pattern.search(img)
        if not m:
            continue

        text_id = m.group(1)
        groups.setdefault(text_id, []).append(img)

    removed = 0

    for text_id in sorted(groups.keys()):

        imgs = groups[text_id]

        if len(imgs) <= keep:
            continue

        keep_imgs = set(random.sample(imgs, keep))

        for img in imgs:

            if img not in keep_imgs:

                os.remove(os.path.join(img_dir, img))
                os.remove(os.path.join(gt_dir, img.replace(".jpg",".gt.txt")))

                removed += 1

    print("Удалено:", removed)


reduce_renders_per_text(
"/content/kab_dataset/train/images",
"/content/kab_dataset/train/gt",
1
)

reduce_renders_per_text(
"/content/kab_dataset/valid/images",
"/content/kab_dataset/valid/gt",
1
)

reduce_renders_per_text(
"/content/kab_dataset/test/images",
"/content/kab_dataset/test/gt",
1
)

Удалено: 990000
Удалено: 55000
Удалено: 55000

## rus+kbd

In [11]:
!apt-get update
!apt-get install -y tesseract-ocr
!apt-get install -y tesseract-ocr-rus
!apt-get install -y libleptonica-dev

!pip install jiwer pandas tqdm

Get:1 https://cli.github.com/packages stable InRelease [3,917 B]
Get:2 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease [3,632 B]
Get:3 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ Packages [87.4 kB]
Get:4 http://security.ubuntu.com/ubuntu jammy-security InRelease [129 kB]
Get:5 https://r2u.stat.illinois.edu/ubuntu jammy InRelease [6,555 B]
Get:6 https://cli.github.com/packages stable/main amd64 Packages [357 B]
Hit:7 http://archive.ubuntu.com/ubuntu jammy InRelease
Get:8 https://r2u.stat.illinois.edu/ubuntu jammy/main all Packages [9,870 kB]
Get:9 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [128 kB]
Get:10 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease [18.1 kB]
Get:11 http://security.ubuntu.com/ubuntu jammy-security/multiverse amd64 Packages [62.6 kB]
Get:12 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease [24.6 kB]
Get:13 https://r2u.stat.illinois.edu/ubuntu jammy/main amd64 Packages [2,934 kB]
Get:14 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [3,829 kB]
Get:15 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy/main amd64 Packages [38.9 kB]
Get:16 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [127 kB]
Get:17 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy/main amd64 Packages [75.3 kB]
Get:18 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [1,615 kB]
Get:19 http://security.ubuntu.com/ubuntu jammy-security/restricted amd64 Packages [6,786 kB]
Get:20 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [1,302 kB]
Get:21 http://archive.ubuntu.com/ubuntu jammy-updates/multiverse amd64 Packages [70.9 kB]
Get:22 http://archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages [7,002 kB]
Get:23 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [4,164 kB]
Get:24 http://archive.ubuntu.com/ubuntu jammy-backports/universe amd64 Packages [35.6 kB]
Get:25 http://archive.ubuntu.com/ubuntu jammy-backports/main amd64 Packages [84.0 kB]
Fetched 38.4 MB in 5s (8,452 kB/s)
Reading package lists... Done
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
tesseract-ocr is already the newest version (4.1.1-2.1build1).
0 upgraded, 0 newly installed, 0 to remove and 141 not upgraded.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  tesseract-ocr-rus
0 upgraded, 1 newly installed, 0 to remove and 141 not upgraded.
Need to get 1,271 kB of archives.
After this operation, 3,877 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy/universe amd64 tesseract-ocr-rus all 1:4.00~git30-7274cfa-1.1 [1,271 kB]
Fetched 1,271 kB in 1s (909 kB/s)
Selecting previously unselected package tesseract-ocr-rus.
(Reading database ... 117540 files and directories currently installed.)
Preparing to unpack .../tesseract-ocr-rus_1%3a4.00~git30-7274cfa-1.1_all.deb ...
Unpacking tesseract-ocr-rus (1:4.00~git30-7274cfa-1.1) ...
Setting up tesseract-ocr-rus (1:4.00~git30-7274cfa-1.1) ...
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  libleptonica-dev
0 upgraded, 1 newly installed, 0 to remove and 141 not upgraded.
Need to get 1,562 kB of archives.
After this operation, 6,390 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libleptonica-dev amd64 1.82.0-3build1 [1,562 kB]
Fetched 1,562 kB in 2s (1,032 kB/s)
Selecting previously unselected package libleptonica-dev.
(Reading database ... 117544 files and directories currently installed.)
Preparing to unpack .../libleptonica-dev_1.82.0-3build1_amd64.deb ...
Unpacking libleptonica-dev (1.82.0-3build1) ...
Setting up libleptonica-dev (1.82.0-3build1) ...
Collecting jiwer
  Downloading jiwer-4.0.0-py3-none-any.whl.metadata (3.3 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (4.67.3)
Requirement already satisfied: click>=8.1.8 in /usr/local/lib/python3.12/dist-packages (from jiwer) (8.3.1)
Collecting rapidfuzz>=3.9.7 (from jiwer)
  Downloading rapidfuzz-3.14.3-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (12 kB)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading jiwer-4.0.0-py3-none-any.whl (23 kB)
Downloading rapidfuzz-3.14.3-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (3.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 54.3 MB/s eta 0:00:00
Installing collected packages: rapidfuzz, jiwer
Successfully installed jiwer-4.0.0 rapidfuzz-3.14.3

In [12]:
!git clone https://github.com/tesseract-ocr/tesstrain
%cd tesstrain

Cloning into 'tesstrain'...
remote: Enumerating objects: 1119, done.
remote: Counting objects: 100% (470/470), done.
remote: Compressing objects: 100% (60/60), done.
remote: Total 1119 (delta 438), reused 410 (delta 410), pack-reused 649 (from 2)
Receiving objects: 100% (1119/1119), 13.52 MiB | 15.50 MiB/s, done.
Resolving deltas: 100% (659/659), done.
/content/tesstrain

In [13]:
import os

os.makedirs("/content/drive/MyDrive/OCR_models", exist_ok=True)
os.makedirs("/content/drive/MyDrive/OCR_results", exist_ok=True)

In [14]:
import subprocess
import pandas as pd
from jiwer import cer, wer
from tqdm import tqdm

def evaluate_ocr(img_dir, gt_dir, model, output_csv):

    results = []
    files = os.listdir(img_dir)

    for img in tqdm(files):

        img_path = os.path.join(img_dir, img)
        out_path = "/content/tmp_out"

        subprocess.run([
            "tesseract",
            img_path,
            out_path,
            "-l",
            model,
            "--psm",
            "7"
        ], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)

        with open(out_path + ".txt") as f:
            pred = f.read().strip()

        with open(os.path.join(gt_dir, img.replace(".jpg",".gt.txt"))) as f:
            gt = f.read().strip()

        gt = " ".join(gt.split())
        pred = " ".join(pred.split())

        results.append({
            "file": img,
            "gt": gt,
            "prediction": pred,
            "cer": cer(gt, pred),
            "wer": wer(gt, pred)
        })

    df = pd.DataFrame(results)

    df.to_csv(output_csv, index=False)

    print("Saved:", output_csv)
    print("CER:", df["cer"].mean())
    print("WER:", df["wer"].mean())

    return df

In [15]:
import os
import shutil
from tqdm import tqdm
import random

train_src_img = "/content/kab_dataset/train/images"
train_src_gt  = "/content/kab_dataset/train/gt"

valid_src_img = "/content/kab_dataset/valid/images"
valid_src_gt  = "/content/kab_dataset/valid/gt"

train_dst = "/content/tesstrain/data/rus_kbd-ground-truth"
valid_dst = "/content/tesstrain/data/rus_kbd-eval"

os.makedirs(train_dst, exist_ok=True)
os.makedirs(valid_dst, exist_ok=True)

random.seed(42)

files = [f for f in os.listdir(train_src_img) if f.endswith(".jpg")]
files = random.sample(files, 10000)

for f in tqdm(files):

    shutil.copy(
        os.path.join(train_src_img, f),
        os.path.join(train_dst, f)
    )

    shutil.copy(
        os.path.join(train_src_gt, f.replace(".jpg",".gt.txt")),
        os.path.join(train_dst, f.replace(".jpg",".gt.txt"))
    )

print("Copy validation data")

for f in tqdm(os.listdir(valid_src_img)):

    shutil.copy(
        os.path.join(valid_src_img, f),
        os.path.join(valid_dst, f)
    )

    shutil.copy(
        os.path.join(valid_src_gt, f.replace(".jpg",".gt.txt")),
        os.path.join(valid_dst, f.replace(".jpg",".gt.txt"))
    )

100%|██████████| 10000/10000 [00:22<00:00, 449.73it/s]

Copy validation data

100%|██████████| 5000/5000 [00:06<00:00, 744.07it/s]

In [16]:
!mkdir -p /content/tesstrain/tessdata

!wget https://github.com/tesseract-ocr/tessdata_best/raw/main/rus.traineddata \
-P /content/tesstrain/tessdata

--2026-03-17 18:14:18--  https://github.com/tesseract-ocr/tessdata_best/raw/main/rus.traineddata
Resolving github.com (github.com)... 140.82.112.4
Connecting to github.com (github.com)|140.82.112.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/tesseract-ocr/tessdata_best/main/rus.traineddata [following]
--2026-03-17 18:14:19--  https://raw.githubusercontent.com/tesseract-ocr/tessdata_best/main/rus.traineddata
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 15301764 (15M) [application/octet-stream]
Saving to: ‘/content/tesstrain/tessdata/rus.traineddata’

rus.traineddata     100%[===================>]  14.59M  --.-KB/s    in 0.07s

2026-03-17 18:14:37 (200 MB/s) - ‘/content/tesstrain/tessdata/rus.traineddata’ saved [15301764/15301764]

In [17]:
%cd /content/tesstrain

/content/tesstrain

In [18]:
from PIL import Image
import os
from tqdm import tqdm

def convert_and_fix(folder):

    converted = 0

    for f in tqdm(os.listdir(folder)):

        path = os.path.join(folder, f)

        if f.endswith(".jpg"):

            img = Image.open(path)
            png_path = path.replace(".jpg", ".png")

            img.save(png_path, dpi=(300,300))
            os.remove(path)

            converted += 1

        elif f.endswith(".png"):

            img = Image.open(path)
            img.save(path, dpi=(300,300))

    print("converted jpg → png:", converted)


convert_and_fix("/content/tesstrain/data/rus_kbd-ground-truth")
convert_and_fix("/content/tesstrain/data/rus_kbd-eval")

100%|██████████| 20000/20000 [02:13<00:00, 149.70it/s]

converted jpg → png: 10000

100%|██████████| 10000/10000 [00:57<00:00, 172.45it/s]

converted jpg → png: 5000

In [19]:
import shutil
import os
import time
import threading

src_dir = "/content/tesstrain/data"
dst_dir = "/content/drive/MyDrive/OCR_models/checkpoints"

os.makedirs(dst_dir, exist_ok=True)

def autosave():
    while True:
        for f in os.listdir(src_dir):
            if "rus_kbd_checkpoint" in f:
                shutil.copy(
                    os.path.join(src_dir, f),
                    os.path.join(dst_dir, f)
                )
                print("Saved:", f)

        time.sleep(300)  # каждые 5 минут

thread = threading.Thread(target=autosave)
thread.daemon = True
thread.start()

In [ ]:
!make training \
MODEL_NAME=rus_kbd \
START_MODEL=rus \
GROUND_TRUTH_DIR=data/rus_kbd-ground-truth \
EVAL_GROUND_TRUTH_DIR=data/rus_kbd-eval \
LANG_TYPE=LINE \
TESSDATA=./tessdata \
MAX_ITERATIONS=4000 \
DEBUG_INTERVAL=500 \
RATIO_TRAIN=0.9 \
NET_SPEC="[1,36,0,1 Ct3,3,16 Mp3,3 Lfys32 Lfx64 O1c]" \
SCROLLVIEW_PATH=/usr/bin/false \
2>&1 | tee /content/train_log.txt

In [29]:
!lstmtraining \
  --traineddata data/rus_kbd/rus_kbd.traineddata \
  --old_traineddata ./tessdata/rus.traineddata \
  --continue_from data/rus/rus_kbd.lstm \
  --learning_rate 0.0001 \
  --model_output data/rus_kbd/checkpoints/rus_kbd \
  --train_listfile data/rus_kbd/list.train \
  --eval_listfile data/rus_kbd/list.eval \
  --max_iterations 4000 \
  --target_error_rate 0.01 \
2>&1 | tee /content/train_log.txt

Loaded file data/rus/rus_kbd.lstm, unpacking...
Warning: LSTMTrainer deserialized an LSTMRecognizer!
Code range changed from 124 to 132!
Num (Extended) outputs,weights in Series:
  1,36,0,1:1, 0
Num (Extended) outputs,weights in Series:
  C3,3:9, 0
  Ft16:16, 160
Total weights = 160
  [C3,3Ft16]:16, 160
  Mp3,3:16, 0
  Lfys64:64, 20736
  Lfx96:96, 61824
  Lrx96:96, 74112
  Lfx512:512, 1247232
  Fc132:132, 67716
Total weights = 1471780
Previous null char=123 mapped to 131
Continuing from data/rus/rus_kbd.lstm
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_028971_Serif_0_1.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_069586_Mono_1_0.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_048734_Sans_1_1.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_023613_Serif_0_0.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_012205_Sans_1_1.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_000790_Mono_1_0.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_059520_Sans_1_0.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_011608_Serif_1_1.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_067707_Mono_1_1.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_065469_Mono_1_0.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_075712_Serif_0_0.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_044715_Mono_0_0.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_009202_Mono_0_0.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_010415_Mono_1_1.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_021728_Sans_1_1.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_050329_Serif_1_0.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_047966_Serif_0_0.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_042631_Mono_0_0.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_016335_Serif_1_0.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_076243_Sans_1_1.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_028153_Serif_0_0.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_083267_Serif_1_1.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_016276_Serif_0_0.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_075545_Serif_0_0.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_055341_Mono_1_0.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_045049_Mono_0_0.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_036551_Mono_0_0.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_019750_Serif_1_0.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_088684_Serif_1_1.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_066800_Sans_0_1.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_045785_Serif_0_0.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_069378_Serif_0_1.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_058852_Mono_1_0.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_061028_Mono_1_1.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_008545_Sans_0_1.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_076060_Sans_0_1.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_032010_Serif_1_1.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_014967_Serif_1_1.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_084452_Serif_1_0.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_089544_Serif_1_1.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_021008_Sans_0_0.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_062209_Sans_0_0.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_037621_Mono_1_0.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_033835_Mono_0_0.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_038955_Sans_0_1.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_018880_Serif_1_1.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_085092_Serif_0_0.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_079207_Serif_1_1.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_034992_Serif_1_1.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_074345_Serif_1_1.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_076178_Mono_1_1.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_045333_Serif_0_0.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_056523_Serif_0_0.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_046325_Mono_1_0.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_039600_Sans_0_0.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_056364_Serif_0_0.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_010466_Serif_0_0.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_047048_Mono_1_0.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_059845_Mono_0_0.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_061964_Sans_0_0.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_016956_Serif_1_0.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_024855_Sans_1_1.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_061244_Mono_1_0.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_046798_Sans_1_1.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_028725_Sans_1_0.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_084636_Mono_0_0.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_064638_Serif_1_0.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_085219_Mono_1_0.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_044554_Serif_1_1.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_075796_Mono_0_1.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_072104_Mono_1_1.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_036255_Mono_0_0.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_012136_Serif_0_0.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_083478_Serif_1_0.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_011713_Serif_1_0.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_040148_Mono_0_0.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_034748_Mono_0_1.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_040789_Serif_1_1.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_054592_Serif_0_1.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_034813_Sans_0_0.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_078556_Mono_1_1.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_013822_Serif_1_1.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_082232_Sans_1_1.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_018476_Mono_0_1.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_003707_Sans_0_0.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_004379_Sans_0_1.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_035427_Serif_1_1.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_026883_Mono_0_0.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_070000_Sans_0_1.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_084548_Sans_1_0.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_004087_Serif_0_0.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_002166_Mono_0_0.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_005975_Serif_1_1.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_085249_Sans_0_1.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_050303_Serif_1_1.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_077408_Serif_0_1.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_044726_Mono_0_1.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_069964_Sans_1_1.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_008834_Serif_0_0.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_015423_Sans_1_0.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_037199_Serif_0_0.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_018971_Serif_0_1.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_061546_Sans_0_0.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_051600_Mono_0_1.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_015471_Serif_0_1.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_088208_Mono_1_0.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_023870_Serif_0_1.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_069974_Serif_1_1.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_011382_Sans_0_0.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_081151_Sans_1_0.lstmf
2 Percent improvement time=99, best error was 100 @ 0
At iteration 99/100/100, Mean rms=1.441%, delta=3.354%, char train=12.355%, word train=40.197%, skip ratio=0%,  New best char error = 12.355 wrote best model:data/rus_kbd/checkpoints/rus_kbd12.355_99.checkpoint wrote checkpoint.

Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_036606_Sans_0_1.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_026731_Mono_0_0.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_012697_Serif_1_1.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_064179_Serif_0_0.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_025377_Mono_0_1.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_082421_Serif_0_0.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_069966_Sans_0_1.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_053564_Mono_1_1.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_075455_Serif_0_1.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_050266_Sans_0_0.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_054679_Serif_0_1.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_037915_Mono_0_1.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_038458_Mono_0_0.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_057039_Mono_1_0.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_000780_Mono_1_1.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_060736_Mono_1_0.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_013501_Sans_0_0.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_048887_Mono_1_0.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_041103_Mono_0_0.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_035685_Sans_1_0.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_066961_Serif_1_1.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_088298_Mono_1_1.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_042781_Serif_1_0.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_079709_Sans_0_1.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_009811_Serif_1_1.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_010180_Mono_0_0.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_055390_Serif_0_1.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_022238_Serif_1_1.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_008479_Serif_1_1.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_010694_Sans_1_0.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_024795_Serif_1_0.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_072069_Sans_1_0.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_063577_Serif_0_0.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_037451_Sans_0_0.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_006314_Mono_1_1.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_061666_Mono_1_1.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_044716_Mono_1_1.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_076065_Mono_0_1.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_020333_Serif_1_1.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_085026_Mono_1_1.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_052241_Sans_1_0.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_037662_Mono_0_1.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_013013_Sans_0_1.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_006462_Sans_0_1.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_063013_Mono_1_1.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_069109_Sans_0_1.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_088077_Sans_1_0.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_036116_Mono_1_0.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_014954_Mono_1_1.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_074713_Serif_1_0.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_018865_Sans_1_0.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_007587_Mono_0_0.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_035752_Serif_0_0.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_088774_Serif_0_1.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_022151_Mono_1_1.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_023782_Serif_0_0.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_089729_Serif_0_1.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_080532_Serif_1_0.lstmf
Loaded 1/1 lines (1-1) of document data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_023864_Mono_1_1.lstmf

### Сохранение

In [31]:
!lstmtraining \
  --stop_training \
  --continue_from data/rus_kbd/checkpoints/rus_kbd_checkpoint \
  --traineddata data/rus_kbd/rus_kbd.traineddata \
  --model_output data/rus_kbd.traineddata

Loaded file data/rus_kbd/checkpoints/rus_kbd_checkpoint, unpacking...

In [33]:
!ls -lh /content/tesstrain/data | grep rus_kbd

drwxr-xr-x 3 root root 4.0K Mar 17 18:40 rus_kbd
drwxr-xr-x 2 root root 1.1M Mar 17 18:17 rus_kbd-eval
-rw-r--r-- 1 root root  77K Mar 17 19:57 rus_kbd.eval_files.txt
drwxr-xr-x 2 root root 3.4M Mar 17 18:40 rus_kbd-ground-truth
-rw-r--r-- 1 root root  12M Mar 17 21:31 rus_kbd.traineddata
-rw-r--r-- 1 root root 689K Mar 17 19:57 rus_kbd.training_files.txt

In [34]:
from google.colab import files
files.download("/content/tesstrain/data/rus_kbd.traineddata")

In [39]:
!zip -r /content/tesstrain_data.zip /content/tesstrain/data
from google.colab import files
files.download('/content/tesstrain_data.zip')

Выходные данные были обрезаны до нескольких последних строк (5000).
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_088846_Serif_0_0.gt.txt (deflated 33%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_076060_Sans_0_1.lstmf (deflated 6%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_076016_Serif_0_0.box (deflated 88%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_071099_Serif_0_0.box (deflated 87%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_083150_Mono_0_0.gt.txt (deflated 25%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_079923_Mono_0_1.lstmf (deflated 6%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_083389_Mono_1_0.png (deflated 4%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_071074_Serif_0_1.lstmf (deflated 7%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_065810_Mono_0_0.gt.txt (deflated 27%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_012676_Sans_0_1.gt.txt (deflated 29%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_054329_Serif_1_1.png (deflated 5%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_067803_Mono_1_1.lstmf (deflated 7%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_000213_Sans_1_1.gt.txt (deflated 31%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_051596_Mono_0_1.lstmf (deflated 6%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_052081_Sans_1_0.lstmf (deflated 6%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_033236_Mono_0_1.lstmf (deflated 6%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_039325_Sans_1_1.box (deflated 88%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_020778_Mono_0_0.box (deflated 87%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_012199_Sans_1_0.lstmf (deflated 7%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_022542_Sans_0_0.box (deflated 88%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_021761_Serif_0_0.box (deflated 87%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_057700_Mono_1_1.lstmf (deflated 7%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_029228_Serif_1_1.box (deflated 88%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_073829_Mono_0_0.gt.txt (deflated 31%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_026400_Serif_0_1.box (deflated 87%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_042112_Mono_0_0.lstmf (deflated 6%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_009601_Sans_1_1.gt.txt (deflated 32%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_016492_Mono_1_0.png (deflated 4%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_065209_Serif_0_0.gt.txt (deflated 35%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_044333_Serif_1_1.png (deflated 5%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_005654_Sans_0_0.png (deflated 3%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_039656_Sans_1_1.png (deflated 5%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_025546_Serif_1_0.png (deflated 3%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_078809_Sans_1_0.box (deflated 88%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_088077_Sans_1_0.lstmf (deflated 6%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_027627_Serif_1_1.png (deflated 6%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_040946_Mono_1_0.lstmf (deflated 7%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_048157_Serif_0_1.png (deflated 5%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_054287_Serif_1_1.gt.txt (deflated 28%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_043245_Serif_1_0.box (deflated 87%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_053258_Sans_1_0.box (deflated 89%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_080142_Sans_0_1.png (deflated 4%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_042566_Sans_0_1.png (deflated 5%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_051073_Sans_0_0.box (deflated 88%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_035937_Sans_0_1.box (deflated 87%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_013170_Mono_0_0.gt.txt (deflated 33%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_068140_Serif_0_1.png (deflated 5%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_005273_Mono_0_1.lstmf (deflated 6%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_057701_Sans_1_1.lstmf (deflated 7%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_067300_Serif_1_1.box (deflated 89%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_029933_Mono_0_0.gt.txt (deflated 33%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_023755_Sans_0_1.lstmf (deflated 6%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_063920_Mono_0_0.box (deflated 87%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_049705_Sans_0_1.png (deflated 4%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_082179_Mono_1_1.png (deflated 5%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_002559_Mono_0_0.gt.txt (deflated 29%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_048643_Mono_0_0.png (deflated 3%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_029004_Serif_1_1.png (deflated 6%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_062837_Serif_0_0.box (deflated 87%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_071017_Mono_1_1.png (deflated 4%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_056777_Serif_1_0.gt.txt (deflated 31%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_037183_Mono_1_0.gt.txt (deflated 39%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_032410_Mono_0_0.gt.txt (deflated 31%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_019992_Serif_1_0.png (deflated 4%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_086467_Sans_1_0.gt.txt (deflated 27%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_010140_Sans_0_0.gt.txt (deflated 37%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_088924_Sans_0_1.gt.txt (deflated 32%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_062161_Mono_0_1.box (deflated 87%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_052231_Mono_0_1.png (deflated 4%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_026305_Mono_0_1.lstmf (deflated 6%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_065626_Serif_1_1.gt.txt (deflated 29%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_030128_Sans_1_1.gt.txt (deflated 27%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_071399_Sans_0_0.lstmf (deflated 6%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_003416_Sans_0_1.gt.txt (deflated 29%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_036981_Sans_1_0.lstmf (deflated 7%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_026360_Mono_1_0.box (deflated 88%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_009886_Mono_0_0.png (deflated 3%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_057678_Serif_1_0.png (deflated 4%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_006567_Sans_1_1.png (deflated 5%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_073098_Serif_1_0.lstmf (deflated 7%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_072784_Serif_0_1.gt.txt (deflated 29%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_013745_Sans_1_1.box (deflated 86%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_023036_Mono_0_0.gt.txt (deflated 22%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_050201_Sans_1_1.box (deflated 87%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_067415_Serif_0_1.png (deflated 5%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_056225_Mono_0_1.lstmf (deflated 6%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_056580_Serif_1_1.gt.txt (deflated 27%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_046936_Sans_0_0.lstmf (deflated 6%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_050575_Serif_0_1.box (deflated 88%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_084404_Sans_0_0.gt.txt (deflated 31%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_016990_Mono_1_1.lstmf (deflated 7%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_084181_Sans_0_0.box (deflated 88%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_050161_Sans_0_0.png (deflated 3%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_005341_Sans_1_0.box (deflated 88%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_000632_Sans_1_1.gt.txt (deflated 34%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_050969_Serif_1_1.gt.txt (deflated 24%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_040986_Sans_0_1.gt.txt (deflated 27%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_014650_Sans_0_0.box (deflated 87%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_083678_Mono_1_1.gt.txt (deflated 37%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_064867_Sans_0_0.png (deflated 3%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_089820_Sans_0_1.png (deflated 4%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_023833_Mono_1_1.gt.txt (deflated 25%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_042693_Mono_0_0.lstmf (deflated 5%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_017578_Serif_0_1.gt.txt (deflated 39%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_086609_Sans_0_0.gt.txt (deflated 31%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_070498_Mono_1_0.lstmf (deflated 7%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_044730_Sans_1_0.box (deflated 88%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_040569_Mono_0_0.gt.txt (deflated 31%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_055081_Sans_1_0.box (deflated 87%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_009773_Serif_0_0.box (deflated 87%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_026883_Mono_0_0.gt.txt (deflated 33%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_072551_Sans_0_1.lstmf (deflated 6%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_050838_Sans_1_1.box (deflated 88%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_010850_Mono_0_0.png (deflated 3%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_040175_Sans_0_1.lstmf (deflated 6%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_026644_Mono_0_0.box (deflated 88%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_039281_Mono_0_0.box (deflated 87%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_020982_Serif_1_0.lstmf (deflated 7%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_052857_Sans_1_1.box (deflated 88%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_006045_Sans_0_1.box (deflated 88%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_075123_Sans_0_0.box (deflated 87%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_077269_Serif_1_0.lstmf (deflated 7%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_087160_Sans_0_1.box (deflated 86%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_012211_Sans_0_0.png (deflated 3%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_010832_Mono_1_1.lstmf (deflated 7%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_064836_Serif_1_1.lstmf (deflated 8%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_037694_Sans_1_0.gt.txt (deflated 29%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_042102_Serif_1_1.gt.txt (deflated 28%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_088262_Serif_1_0.gt.txt (deflated 35%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_015660_Mono_1_0.gt.txt (deflated 28%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_001155_Serif_0_0.gt.txt (deflated 34%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_004453_Serif_1_1.lstmf (deflated 8%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_088774_Serif_0_1.box (deflated 88%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_032664_Serif_1_1.png (deflated 5%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_046307_Mono_0_0.box (deflated 87%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_002249_Sans_0_0.lstmf (deflated 6%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_049014_Sans_1_1.box (deflated 87%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_074941_Sans_1_0.gt.txt (deflated 34%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_027677_Serif_0_0.gt.txt (deflated 26%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_059984_Serif_0_0.gt.txt (deflated 29%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_032136_Serif_0_1.png (deflated 5%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_046773_Sans_1_0.lstmf (deflated 6%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_078327_Sans_1_1.box (deflated 88%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_075508_Mono_0_1.png (deflated 4%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_068713_Mono_1_0.gt.txt (deflated 25%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_030702_Serif_0_1.lstmf (deflated 8%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_062118_Mono_0_1.lstmf (deflated 6%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_043881_Sans_1_1.png (deflated 5%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_037641_Serif_1_1.lstmf (deflated 8%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_032265_Sans_0_1.box (deflated 87%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_009442_Sans_1_0.gt.txt (deflated 27%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_011667_Sans_1_1.gt.txt (deflated 32%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_037402_Serif_1_0.box (deflated 86%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_042366_Serif_0_1.png (deflated 5%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_020016_Mono_0_0.png (deflated 4%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_076866_Sans_0_1.gt.txt (deflated 25%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_078295_Mono_1_1.png (deflated 5%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_083145_Mono_1_0.box (deflated 88%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_002648_Serif_0_0.png (deflated 4%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_030423_Mono_1_0.lstmf (deflated 6%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_034589_Serif_0_1.png (deflated 5%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_062155_Serif_1_1.box (deflated 87%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_022603_Mono_1_1.png (deflated 4%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_008884_Sans_0_1.png (deflated 4%)
  adding: content/tesstrain/data/rus_kbd-ground-truth/Kabard_NoOCR_balanced_sampled_075674_Mono_0_0.gt.txt (deflated 27%)

In [35]:
import shutil

shutil.copy(
    "/content/tesstrain/data/rus_kbd.traineddata",
    "/content/drive/MyDrive/OCR_models/rus_kbd.traineddata"
)

'/content/drive/MyDrive/OCR_models/rus_kbd.traineddata'

In [40]:
!cp /content/tesstrain/data/rus_kbd.traineddata /usr/share/tesseract-ocr/4.00/tessdata/

In [41]:
evaluate_ocr(
    "/content/kab_dataset/test/images",
    "/content/kab_dataset/test/gt",
    "rus_kbd",
    "/content/drive/MyDrive/OCR_results/rus_kbd_on_kbd_test.csv"
)

100%|██████████| 5000/5000 [1:12:35<00:00,  1.15it/s]

Saved: /content/drive/MyDrive/OCR_results/rus_kbd_on_kbd_test.csv
CER: 0.002281709436769704
WER: 0.016938178266103915

,file,gt,prediction,cer,wer
0,Kabard_NoOCR_balanced_sampled_097549_Serif_0_0...,"Ищхъэрэм щыпсэухэм я мызакъуэу, ар хамэ къэрал...","Ищхъэрэм щыпсэухэм я мызакъуэу, ар хамэ къэрал...",0.00000,0.000000
1,Kabard_NoOCR_balanced_sampled_099810_Mono_1_1.jpg,"и мэлым и бжьакъуитIыр Уи натIэгум къытеукIэ, ...","и мэлым и бжьакъуитIыр Уи натIэгум къытеукIэ, ...",0.00000,0.000000
2,Kabard_NoOCR_balanced_sampled_098496_Serif_1_0...,"15ЛIы гуэр къыхуэзащ абы, губгъуэм игъуэщыхьау...","I5ЛIы гуэр къыхуэзащ абы, губгъуэм игъуэщыхьау...",0.01087,0.071429
3,Kabard_NoOCR_balanced_sampled_097696_Serif_1_1...,"Нэхъыщхьэр, нэгъуэщIхэм ядэджэгуху зэпэщIэтыны...","Нэхъыщхьэр, нэгъуэщIхэм ядэджэгуху зэпэщIэтыны...",0.00000,0.000000
4,Kabard_NoOCR_balanced_sampled_097260_Mono_1_0.jpg,"Сыт хуэдизу цIыхухэр гуапэу къытхущымытми, адэ...","Сыт хуэдизу цIыхухэр гуапэу къытхущымытми, адэ...",0.00000,0.000000
...,...,...,...,...,...
4995,Kabard_NoOCR_balanced_sampled_099049_Serif_1_1...,Лэжьыгъэр нэхъ кIащхъэ щыхъу бжьыхьэр я благъэ...,Лэжьыгъэр нэхъ кIащхъэ щыхъу бжьыхьэр я благъэ...,0.00000,0.000000
4996,Kabard_NoOCR_balanced_sampled_099237_Serif_0_1...,"Жьакуэ къуажэм дэс, егъэджакIуэ, щIэныгъэм пщI...","Жьакуэ къуажэм дэс, егъэджакIуэ, щIэныгъэм пщI...",0.00000,0.000000
4997,Kabard_NoOCR_balanced_sampled_099175_Mono_0_1.jpg,"Зыри зэрылъэмыкIыр къэжэрхэм къащIэмэ, гугъущэ...","Зыри зэрылъэмыкIыр къэжэрхэм къащIэмэ, гугъущэ...",0.00000,0.000000
4998,Kabard_NoOCR_balanced_sampled_098610_Sans_0_0.jpg,КъБР-M и Президентым и деж щыIэ Жылагъуэ-чэндж...,КъБР-I и Президентым и деж щыIэ Жылагъуэ-чэндж...,0.02381,0.375000
4999,Kabard_NoOCR_balanced_sampled_096614_Mono_1_1.jpg,"Ауэ папэ апхуэдэу лэжьэфынутэкъым, къимылэжьа ...","Ауэ папэ апхуэдэу лэжьэфынутэкъым, къимылэжьа ...",0.00000,0.000000

In [42]:
import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/OCR_results/rus_kbd_on_kbd_test.csv')
df.head()  # покажет первые 5 строк

,file,gt,prediction,cer,wer
0,Kabard_NoOCR_balanced_sampled_097549_Serif_0_0...,"Ищхъэрэм щыпсэухэм я мызакъуэу, ар хамэ къэрал...","Ищхъэрэм щыпсэухэм я мызакъуэу, ар хамэ къэрал...",0.00000,0.000000
1,Kabard_NoOCR_balanced_sampled_099810_Mono_1_1.jpg,"и мэлым и бжьакъуитIыр Уи натIэгум къытеукIэ, ...","и мэлым и бжьакъуитIыр Уи натIэгум къытеукIэ, ...",0.00000,0.000000
2,Kabard_NoOCR_balanced_sampled_098496_Serif_1_0...,"15ЛIы гуэр къыхуэзащ абы, губгъуэм игъуэщыхьау...","I5ЛIы гуэр къыхуэзащ абы, губгъуэм игъуэщыхьау...",0.01087,0.071429
3,Kabard_NoOCR_balanced_sampled_097696_Serif_1_1...,"Нэхъыщхьэр, нэгъуэщIхэм ядэджэгуху зэпэщIэтыны...","Нэхъыщхьэр, нэгъуэщIхэм ядэджэгуху зэпэщIэтыны...",0.00000,0.000000
4,Kabard_NoOCR_balanced_sampled_097260_Mono_1_0.jpg,"Сыт хуэдизу цIыхухэр гуапэу къытхущымытми, адэ...","Сыт хуэдизу цIыхухэр гуапэу къытхущымытми, адэ...",0.00000,0.000000

In [43]:
from google.colab import files

files.download('/content/drive/MyDrive/OCR_results/rus_kbd_on_kbd_test.csv')

In [44]:
!zip -r /content/kab_dataset_10k.zip /content/kab_dataset
from google.colab import files
files.download('/content/kab_dataset_10k.zip')

Выходные данные были обрезаны до нескольких последних строк (5000).
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_024343_Sans_0_0.gt.txt (deflated 34%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_043718_Mono_0_0.gt.txt (deflated 30%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_035290_Serif_1_1.gt.txt (deflated 27%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_018147_Sans_0_1.gt.txt (deflated 28%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_075367_Sans_0_0.gt.txt (deflated 25%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_011193_Serif_1_1.gt.txt (deflated 23%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_012273_Serif_1_1.gt.txt (deflated 29%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_085526_Serif_0_1.gt.txt (deflated 31%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_059569_Serif_1_1.gt.txt (deflated 21%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_057903_Sans_0_1.gt.txt (deflated 31%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_064735_Mono_0_1.gt.txt (deflated 26%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_034338_Sans_0_1.gt.txt (deflated 27%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_051113_Sans_1_0.gt.txt (deflated 36%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_088232_Mono_0_0.gt.txt (deflated 28%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_042165_Serif_0_1.gt.txt (deflated 31%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_064362_Sans_1_0.gt.txt (deflated 30%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_012056_Serif_1_1.gt.txt (deflated 31%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_040616_Mono_0_1.gt.txt (deflated 31%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_016976_Serif_1_0.gt.txt (deflated 33%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_065699_Mono_1_1.gt.txt (deflated 29%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_015235_Mono_1_0.gt.txt (deflated 32%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_042998_Serif_1_0.gt.txt (deflated 33%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_011030_Serif_0_0.gt.txt (deflated 34%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_050918_Serif_1_1.gt.txt (deflated 28%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_020392_Mono_0_0.gt.txt (deflated 31%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_020774_Mono_1_1.gt.txt (deflated 31%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_027493_Mono_0_1.gt.txt (deflated 32%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_043309_Mono_1_1.gt.txt (deflated 39%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_040024_Mono_1_0.gt.txt (deflated 29%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_081922_Mono_1_1.gt.txt (deflated 24%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_012957_Mono_1_0.gt.txt (deflated 17%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_045529_Mono_0_0.gt.txt (deflated 32%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_087936_Serif_1_0.gt.txt (deflated 31%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_001747_Serif_1_0.gt.txt (deflated 33%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_035664_Serif_1_1.gt.txt (deflated 34%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_083297_Mono_0_1.gt.txt (deflated 29%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_051068_Sans_0_0.gt.txt (deflated 34%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_069033_Sans_1_1.gt.txt (deflated 34%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_038659_Sans_0_1.gt.txt (deflated 31%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_082875_Mono_0_0.gt.txt (deflated 31%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_066973_Sans_0_1.gt.txt (deflated 30%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_053572_Serif_0_1.gt.txt (deflated 28%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_036858_Sans_1_1.gt.txt (deflated 25%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_026881_Sans_1_0.gt.txt (deflated 28%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_056946_Sans_0_0.gt.txt (deflated 30%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_001730_Mono_0_1.gt.txt (deflated 32%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_034050_Mono_1_1.gt.txt (deflated 27%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_036531_Mono_0_0.gt.txt (deflated 34%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_029116_Mono_0_1.gt.txt (deflated 28%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_020629_Sans_0_0.gt.txt (deflated 33%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_020820_Sans_1_0.gt.txt (deflated 30%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_018651_Serif_1_0.gt.txt (deflated 33%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_058996_Mono_1_1.gt.txt (deflated 36%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_033559_Serif_1_0.gt.txt (deflated 24%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_063800_Serif_0_0.gt.txt (deflated 27%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_043606_Serif_0_1.gt.txt (deflated 27%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_029200_Mono_1_0.gt.txt (deflated 26%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_046631_Mono_1_0.gt.txt (deflated 34%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_001034_Sans_1_0.gt.txt (deflated 35%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_019661_Mono_0_0.gt.txt (deflated 33%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_013227_Mono_1_0.gt.txt (deflated 30%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_023294_Serif_0_0.gt.txt (deflated 28%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_044488_Sans_0_1.gt.txt (deflated 20%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_002749_Serif_0_1.gt.txt (deflated 24%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_017682_Sans_1_1.gt.txt (deflated 23%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_072022_Sans_1_1.gt.txt (deflated 31%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_031785_Serif_0_0.gt.txt (deflated 29%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_078084_Serif_1_0.gt.txt (deflated 28%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_051417_Sans_0_1.gt.txt (deflated 25%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_054075_Sans_1_0.gt.txt (deflated 28%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_040259_Serif_0_0.gt.txt (deflated 30%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_074891_Serif_1_1.gt.txt (deflated 31%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_066556_Sans_1_0.gt.txt (deflated 31%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_014718_Serif_0_1.gt.txt (deflated 29%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_017046_Mono_0_1.gt.txt (deflated 32%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_004210_Mono_0_1.gt.txt (deflated 29%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_027199_Mono_1_0.gt.txt (deflated 36%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_082675_Sans_0_0.gt.txt (deflated 29%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_055448_Serif_1_1.gt.txt (deflated 30%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_016135_Mono_0_1.gt.txt (deflated 34%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_019614_Serif_0_1.gt.txt (deflated 33%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_041559_Sans_0_0.gt.txt (deflated 28%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_029523_Serif_0_0.gt.txt (deflated 37%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_048355_Serif_0_1.gt.txt (deflated 28%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_032617_Sans_1_1.gt.txt (deflated 23%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_058837_Serif_0_1.gt.txt (deflated 33%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_010627_Mono_0_0.gt.txt (deflated 27%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_026834_Mono_1_1.gt.txt (deflated 31%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_023854_Mono_0_0.gt.txt (deflated 36%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_013821_Serif_1_1.gt.txt (deflated 27%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_081358_Sans_1_1.gt.txt (deflated 31%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_060460_Mono_1_1.gt.txt (deflated 31%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_089949_Serif_0_1.gt.txt (deflated 33%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_073421_Sans_0_1.gt.txt (deflated 36%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_026080_Sans_0_0.gt.txt (deflated 31%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_008757_Sans_0_1.gt.txt (deflated 31%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_029675_Serif_0_1.gt.txt (deflated 34%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_033111_Serif_0_0.gt.txt (deflated 26%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_080035_Mono_0_0.gt.txt (deflated 26%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_067399_Sans_1_1.gt.txt (deflated 31%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_051803_Serif_1_1.gt.txt (deflated 28%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_031921_Sans_0_1.gt.txt (deflated 31%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_032251_Sans_1_1.gt.txt (deflated 27%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_075822_Serif_1_1.gt.txt (deflated 31%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_076476_Serif_0_0.gt.txt (deflated 30%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_050411_Serif_0_1.gt.txt (deflated 25%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_025977_Mono_1_1.gt.txt (deflated 29%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_063905_Serif_0_1.gt.txt (deflated 29%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_010818_Serif_0_1.gt.txt (deflated 30%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_089680_Serif_1_0.gt.txt (deflated 26%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_036334_Mono_0_1.gt.txt (deflated 33%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_060562_Mono_1_0.gt.txt (deflated 24%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_084197_Serif_1_1.gt.txt (deflated 33%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_065324_Mono_0_1.gt.txt (deflated 32%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_072341_Serif_0_1.gt.txt (deflated 36%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_073549_Mono_1_1.gt.txt (deflated 25%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_084989_Sans_0_0.gt.txt (deflated 22%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_033993_Serif_1_0.gt.txt (deflated 26%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_058219_Sans_0_0.gt.txt (deflated 23%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_053611_Serif_1_0.gt.txt (deflated 33%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_062940_Mono_0_1.gt.txt (deflated 30%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_014696_Sans_0_0.gt.txt (deflated 31%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_007627_Serif_1_0.gt.txt (deflated 31%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_038910_Mono_0_1.gt.txt (deflated 28%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_088324_Mono_0_0.gt.txt (deflated 31%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_057881_Serif_1_0.gt.txt (deflated 28%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_013424_Sans_0_0.gt.txt (deflated 29%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_007398_Sans_1_1.gt.txt (deflated 32%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_081486_Serif_1_0.gt.txt (deflated 24%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_035827_Mono_0_0.gt.txt (deflated 34%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_058785_Sans_0_0.gt.txt (deflated 24%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_000846_Sans_1_0.gt.txt (deflated 25%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_038226_Sans_1_0.gt.txt (deflated 28%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_023966_Sans_0_1.gt.txt (deflated 27%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_071955_Sans_1_1.gt.txt (deflated 27%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_006682_Serif_1_0.gt.txt (deflated 32%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_088393_Serif_1_1.gt.txt (deflated 27%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_035109_Serif_1_0.gt.txt (deflated 26%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_035299_Sans_1_0.gt.txt (deflated 25%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_016830_Serif_0_1.gt.txt (deflated 39%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_023472_Sans_0_0.gt.txt (deflated 32%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_051949_Sans_0_0.gt.txt (deflated 29%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_020027_Serif_1_0.gt.txt (deflated 33%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_041871_Sans_1_1.gt.txt (deflated 30%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_038489_Sans_1_1.gt.txt (deflated 27%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_058787_Mono_0_1.gt.txt (deflated 31%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_025050_Mono_1_0.gt.txt (deflated 38%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_002591_Serif_1_0.gt.txt (deflated 23%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_023471_Sans_0_1.gt.txt (deflated 25%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_063887_Serif_0_1.gt.txt (deflated 34%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_036354_Serif_1_1.gt.txt (deflated 34%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_004088_Mono_0_0.gt.txt (deflated 28%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_026098_Serif_1_0.gt.txt (deflated 29%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_072644_Serif_1_0.gt.txt (deflated 31%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_018979_Sans_0_0.gt.txt (deflated 31%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_038082_Sans_0_0.gt.txt (deflated 28%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_054748_Serif_1_1.gt.txt (deflated 22%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_050697_Serif_0_1.gt.txt (deflated 34%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_077918_Mono_1_1.gt.txt (deflated 33%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_028320_Sans_0_1.gt.txt (deflated 31%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_086550_Mono_0_1.gt.txt (deflated 33%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_009990_Mono_1_1.gt.txt (deflated 27%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_085093_Sans_0_0.gt.txt (deflated 26%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_008800_Mono_1_1.gt.txt (deflated 31%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_008415_Mono_1_0.gt.txt (deflated 25%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_004729_Sans_0_0.gt.txt (deflated 30%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_047323_Serif_1_1.gt.txt (deflated 33%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_017272_Serif_0_1.gt.txt (deflated 33%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_073893_Serif_1_1.gt.txt (deflated 33%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_081495_Serif_1_1.gt.txt (deflated 34%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_030597_Serif_0_1.gt.txt (deflated 31%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_062946_Mono_1_0.gt.txt (deflated 33%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_033852_Serif_1_1.gt.txt (deflated 27%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_074457_Sans_1_1.gt.txt (deflated 29%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_060231_Mono_0_1.gt.txt (deflated 30%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_056436_Sans_1_1.gt.txt (deflated 30%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_063460_Mono_0_0.gt.txt (deflated 28%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_055363_Mono_1_1.gt.txt (deflated 30%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_075139_Sans_1_0.gt.txt (deflated 31%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_039985_Mono_1_0.gt.txt (deflated 19%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_043011_Mono_1_0.gt.txt (deflated 32%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_036579_Serif_0_1.gt.txt (deflated 30%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_060292_Serif_0_0.gt.txt (deflated 30%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_085385_Serif_0_0.gt.txt (deflated 32%)
  adding: content/kab_dataset/train/gt/Kabard_NoOCR_balanced_sampled_067651_Serif_1_0.gt.txt (deflated 27%)

In [ ]:
#evaluate_ocr(
    #"/content/ady_dataset/test/images",
    #"/content/ady_dataset/test/gt",
    #"rus_kbd",
    #"/content/drive/MyDrive/OCR_results/rus_kbd_on_ady_test.csv"
#)

In [ ]:
#evaluate_ocr(
 #   "/content/ady_kbd_test/images",
  #  "/content/ady_kbd_test/gt",
   # "rus_kbd",
    #"/content/drive/MyDrive/OCR_results/rus_kbd_on_ady_kbd_test.csv"
#)